class MockLLM {
    async generateCode(prompt, model) {
        console.log(`[MockLLM] Generating code for: "${prompt}" with model: ${model}`);

        // Simulate network delay
        await new Promise(resolve => setTimeout(resolve, 500));

        return {
            script: `extends Node\n\nfunc _ready():\n\tprint("Generated by YUGA AI (${model})")\n\t# Prompt: ${prompt}`,
            explanation: "Mock explanation for " + prompt
        };
    }

    async debugCode(script, error, model) {
        console.log(`[MockLLM] Debugging code with error: "${error}"`);
        await new Promise(resolve => setTimeout(resolve, 500));

        return {
            script: script + "\n# Fixed error: " + error,
            explanation: "Added a fix comment for the reported error."
        };
    }

    async generateTexture(prompt) {
        console.log(`[MockLLM] Generating texture for: "${prompt}"`);
        await new Promise(resolve => setTimeout(resolve, 500));
        // Return a 1x1 red pixel mock base64
        return {
            data: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
            type: "texture",
            explanation: "Generated mock red texture."
        };
    }

    async generateModel(prompt) {
        console.log(`[MockLLM] Generating model for: "${prompt}"`);
        await new Promise(resolve => setTimeout(resolve, 500));
        return {
            data: "v 0.0 0.0 0.0\nv 1.0 0.0 0.0\nv 0.0 1.0 0.0\nf 1 2 3",
            type: "model",
            explanation: "Generated mock triangle OBJ."
        };
    }

    async generateScene(prompt) {
        console.log(`[MockLLM] Generating scene for: "${prompt}"`);
        await new Promise(resolve => setTimeout(resolve, 500));

        // Mock Scene Tree JSON
        return {
            tree: {
                name: "LevelRoot",
                type: "Node2D",
                children: [
                    {
                        name: "Player",
                        type: "CharacterBody2D",
                        children: [
                            {
                                name: "Sprite",
                                type: "Sprite2D"
                            },
                            {
                                name: "Collision",
                                type: "CollisionShape2D"
                            }
                        ]
                    },
                    {
                        name: "Ground",
                        type: "StaticBody2D",
                        children: [
                            {
                                name: "Collision",
                                type: "CollisionShape2D"
                            }
                        ]
                    }
                ]
            },
            explanation: "Generated a basic level structure with Player and Ground."
        };
    }

    async planTask(prompt) {
        console.log(`[MockLLM] Planning task for: "${prompt}"`);
        await new Promise(resolve => setTimeout(resolve, 500));

        // Mock Plan
        return {
            steps: [
                { type: "code", prompt: "Create a simple PlayerController script for a platformer" },
                { type: "asset", prompt: "A red robot character sprite" },
                { type: "scene", prompt: "A basic platformer level with Player and Ground" }
            ],
            explanation: "Mock plan created."
        };
    }

    async transcribe(audioBuffer) {
        console.log(`[MockLLM] Transcribing audio buffer of size: ${audioBuffer.length}`);
        await new Promise(resolve => setTimeout(resolve, 500));
        return {
            text: "Mock voice command: Create a blue cube"
        };
    }
}

module.exports = new MockLLM();
