const OpenAI = require('openai');

class OpenAILLM {
    constructor() {
        // Initialize OpenAI with API key from environment
        const apiKey = process.env.OPENAI_API_KEY;
        const baseURL = process.env.OPENAI_BASE_URL; // Optional custom endpoint

        if (!apiKey) {
            console.warn("[OpenAILLM] No OPENAI_API_KEY found. OpenAI provider will fail if used.");
            this.openai = null;
        } else {
            const config = { apiKey: apiKey };
            if (baseURL) {
                console.log(`[OpenAILLM] Using custom Base URL: ${baseURL}`);
                config.baseURL = baseURL;
            }
            this.openai = new OpenAI(config);
        }

        // Allow overriding the default model (e.g., 'llama3-70b-8192' for Groq)
        this.defaultModel = process.env.OPENAI_MODEL_DEFAULT || "gpt-4o";
        console.log(`[OpenAILLM] Default model set to: ${this.defaultModel}`);
    }

    async generateCode(prompt, model) {
        const targetModel = model || this.defaultModel;
        console.log(`[OpenAILLM] Generating code for: "${prompt}" with model: ${targetModel}`);

        try {
            const completion = await this.openai.chat.completions.create({
                messages: [
                    { role: "system", content: "You are an expert Godot 4 GDScript developer. Output ONLY valid GDScript code. Do not wrap in markdown blocks." },
                    { role: "user", content: prompt }
                ],
                model: targetModel,
            });

            const script = completion.choices[0].message.content.trim();
            // Basic cleanup if model adds markdown despite instructions
            const cleanScript = script.replace(/```gdscript/g, "").replace(/```/g, "");

            return {
                script: cleanScript,
                explanation: "Generated by OpenAI (" + (model || "gpt-4o") + ")"
            };
        } catch (error) {
            console.error("[OpenAILLM] Error generating code:", error);
            throw error;
        }
    }

    async debugCode(script, error, model) {
        console.log(`[OpenAILLM] Debugging code...`);

        try {
            const completion = await this.openai.chat.completions.create({
                messages: [
                    { role: "system", content: "You are an expert Godot 4 GDScript debugger. Fix the script based on the error. Output ONLY the fixed GDScript code." },
                    { role: "user", content: `Script:\n${script}\n\nError:\n${error}\n\nFix the script.` }
                ],
                model: model || this.defaultModel,
            });

            const fixedScript = completion.choices[0].message.content.trim().replace(/```gdscript/g, "").replace(/```/g, "");

            return {
                script: fixedScript,
                explanation: "Fixed by OpenAI"
            };
        } catch (err) {
            console.error("[OpenAILLM] Error debugging code:", err);
            throw err;
        }
    }

    async generateTexture(prompt) {
        console.log(`[OpenAILLM] Generating texture for: "${prompt}"`);
        try {
            const response = await this.openai.images.generate({
                model: this.defaultModel,
                prompt: "Seamless texture, " + prompt,
                n: 1,
                size: "1024x1024",
                response_format: "b64_json"
            });

            return {
                data: response.data[0].b64_json,
                type: "texture",
                explanation: "Generated by DALL-E 3"
            };
        } catch (err) {
            console.error("[OpenAILLM] Error generating texture:", err);
            throw err;
        }
    }

    async generateModel(prompt) {
        console.log(`[OpenAILLM] Model generation not fully supported via API yet. Returning Mock.`);
        return {
            data: "v 0.0 0.0 0.0\nv 1.0 0.0 0.0\nv 0.0 1.0 0.0\nf 1 2 3",
            type: "model",
            explanation: "OpenAI does not generate 3D models directly yet. Returning mock."
        };
    }

    async generateScene(prompt) {
        console.log(`[OpenAILLM] Generating scene for: "${prompt}"`);
        try {
            const completion = await this.openai.chat.completions.create({
                messages: [
                    {
                        role: "system", content: `You are a helper that generates Godot 4 Scene Trees in JSON format.
Output a JSON object with a "tree" property.
The "tree" object must have: "name" (string), "type" (Godot Node Class), "children" (array of similar objects), and optional "properties" (dictionary).
Valid types: Node2D, Sprite2D, CharacterBody2D, CollisionShape2D, etc.
Example: { "tree": { "name": "Root", "type": "Node2D", "children": [] } }` },
                    { role: "user", content: prompt }
                ],
                model: model || this.defaultModel,
                response_format: { type: "json_object" }
            });

            const result = JSON.parse(completion.choices[0].message.content);
            return {
                tree: result.tree,
                explanation: "Generated scene tree by OpenAI"
            };
        } catch (err) {
            console.error("[OpenAILLM] Error generating scene:", err);
            throw err;
        }
    }

    async planTask(prompt) {
        console.log(`[OpenAILLM] Planning task for: "${prompt}"`);

        try {
            const completion = await this.openai.chat.completions.create({
                messages: [
                    {
                        role: "system", content: `You are an AI Task Planner for a Godot 4 Game Engine.
Break down the user's request into a sequential list of steps.
The steps must be one of the following types: "code", "asset", or "scene".
Output a JSON object with a "steps" property, which is an array of objects.
Each step object must have: "type" (string) and "prompt" (string, detailed instruction for that specific step).
Example: { "steps": [{ "type": "asset", "prompt": "mario sprite" }, { "type": "code", "prompt": "mario movement script" }] }` },
                    { role: "user", content: prompt }
                ],
                model: model || this.defaultModel,
                response_format: { type: "json_object" }
            });

            const result = JSON.parse(completion.choices[0].message.content);
            return {
                steps: result.steps,
                explanation: "Plan generated by OpenAI"
            };
        } catch (err) {
            console.error("[OpenAILLM] Error planning task:", err);
            throw err;
        }
    }

    async transcribe(audioBuffer) {
        console.log(`[OpenAILLM] Transcribing audio...`);
        try {
            // We need to create a File object or similar for the API.
            // Since we are in Node, we can use the 'toFile' helper from openai or just pass a stream with filename.
            const file = await OpenAI.toFile(audioBuffer, "audio.wav");

            const transcription = await this.openai.audio.transcriptions.create({
                file: file,
                model: "whisper-1",
            });

            return {
                text: transcription.text
            };
        } catch (err) {
            console.error("[OpenAILLM] Error transcribing audio:", err);
            throw err;
        }
    }
}

module.exports = new OpenAILLM();
