const https = require('https');

class ScenarioProvider {
    constructor() {
        this.apiKey = process.env.SCENARIO_API_KEY;
        this.apiSecret = process.env.SCENARIO_API_SECRET;
        this.modelId = process.env.SCENARIO_MODEL_ID;

        if (!this.apiKey || !this.apiSecret) {
            console.warn("[ScenarioProvider] SCENARIO_API_KEY or SCENARIO_API_SECRET missing. Provider will fail.");
        }
    }

    async generateTexture(prompt) {
        console.log(`[ScenarioProvider] Generating texture for: "${prompt}"`);

        if (!this.modelId) {
            return { error: "SCENARIO_MODEL_ID is not configured in .env" };
        }

        try {
            const imageData = await this._generateImage(prompt);
            return {
                data: imageData, // Base64 or URL? We need base64 for Godot usually, or we pass URL and plugin downloads it. 
                // Godot plugin expects base64 currently. I will convert if necessary.
                type: "texture",
                explanation: "Generated by Scenario.com"
            };
        } catch (error) {
            console.error("[ScenarioProvider] Error:", error);
            return { error: "Scenario generation failed." };
        }
    }

    async generateModel(prompt) {
        return {
            data: null,
            explanation: "Scenario 3D generation not yet implemented in this provider."
        };
    }

    async _generateImage(prompt) {
        const authString = Buffer.from(`${this.apiKey}:${this.apiSecret}`).toString('base64');

        // Correct payload based on Swagger (Top-level properties)
        const payload = JSON.stringify({
            modelId: this.modelId,
            prompt: prompt,
            numInferenceSteps: 50, // Standard default
            guidance: 7,
            width: 512,
            height: 512
        });

        // Correct URL based on Swagger (/v1/generate/txt2img)
        const triggerUrl = `https://api.cloud.scenario.com/v1/generate/txt2img`;

        console.log(`[ScenarioProvider] Triggering inference on model ${this.modelId}...`);

        const inference = await this._makeRequest(triggerUrl, 'POST', authString, payload);

        // Response wrapper might be different too. Swagger says "PostTxt2imgInferencesResponse".
        // Usually returns { inference: { id: "..." } } based on typical Scenario usage.
        const inferenceId = inference.inference.id;

        console.log(`[ScenarioProvider] Job started: ${inferenceId}. Polling for result...`);

        // Step 2: Poll for completion
        let attempts = 0;
        while (attempts < 30) { // Timeout after ~60s
            await new Promise(r => setTimeout(r, 2000));

            // Polling endpoint usually remains /models/{id}/inferences/{id} or universal /jobs/{id}?
            // Swagger has /jobs/{jobId} (Line 2189). 
            // Let's try /models/{modelId}/inferences/{inferenceId} first as it's standard, but fall back if needed.
            // Actually, for txt2img the ID returned is an inference ID.
            const pollUrl = `https://api.cloud.scenario.com/v1/models/${this.modelId}/inferences/${inferenceId}`;
            const pollResult = await this._makeRequest(pollUrl, 'GET', authString);

            if (pollResult.inference.status === 'succeeded') {
                const imageUrl = pollResult.inference.images[0].url;
                console.log(`[ScenarioProvider] Success! Image URL: ${imageUrl}`);
                return await this._downloadImageAsBase64(imageUrl);
            } else if (pollResult.inference.status === 'failed') {
                throw new Error("Scenario inference failed.");
            }

            attempts++;
        }
        throw new Error("Scenario generation timed out.");
    }

    _makeRequest(url, method, auth, body = null) {
        return new Promise((resolve, reject) => {
            const options = {
                method: method,
                headers: {
                    'Authorization': `Basic ${auth}`,
                    'Content-Type': 'application/json',
                    'Accept': 'application/json'
                }
            };

            const req = https.request(url, options, (res) => {
                let data = '';
                res.on('data', chunk => data += chunk);
                res.on('end', () => {
                    if (res.statusCode >= 200 && res.statusCode < 300) {
                        try {
                            resolve(JSON.parse(data));
                        } catch (e) {
                            reject(e);
                        }
                    } else {
                        reject(new Error(`API Error ${res.statusCode}: ${data}`));
                    }
                });
            });

            req.on('error', reject);
            if (body) req.write(body);
            req.end();
        });
    }

    _downloadImageAsBase64(url) {
        return new Promise((resolve, reject) => {
            https.get(url, (res) => {
                const chunks = [];
                res.on('data', chunk => chunks.push(chunk));
                res.on('end', () => {
                    const buffer = Buffer.concat(chunks);
                    resolve(buffer.toString('base64'));
                });
            }).on('error', reject);
        });
    }
}

module.exports = ScenarioProvider;
